# Generated by Django 4.2.4 on 2023-08-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updown', '0002_alter_customer_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='documents',
            field=models.ManyToManyField(blank=True, null=True, related_name='customers', to='updown.crmdocument'),
        ),
    ]
