# Generated by Django 4.2.1 on 2023-08-24 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updown', '0003_alter_customer_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='documents',
        ),
        migrations.AddField(
            model_name='customer',
            name='documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='updown.crmdocument'),
        ),
    ]
