# Generated by Django 4.2.1 on 2023-08-24 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updown', '0004_remove_customer_documents_customer_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='documents',
        ),
        migrations.AddField(
            model_name='crmdocument',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='updown.customer'),
        ),
    ]
